-- 1. AC_BASIC
CREATE TABLE AC_BASIC (
    NAME VARCHAR2(255) PRIMARY KEY,
    URL VARCHAR2(500),
    INFO_AVIONICS CLOB,
    INFO_ENGINE VARCHAR2(255),
    INFO_ENGINE_TYPE VARCHAR2(100),
    INFO_WING_TIPS VARCHAR2(100),
    INFO_SEATS_TOTAL NUMBER,
    INFO_SEATS_ECONOMY NUMBER,
    INFO_SEATS_BUSINESS NUMBER,
    INFO_SEATS_FIRST NUMBER
);

-- 2. AC_RANGE_ALT
CREATE TABLE AC_RANGE_ALT (
    NAME VARCHAR2(255),
    PERF_RANGE_KM NUMBER,
    PERF_RANGE_NM NUMBER,
    PERF_RANGE_MI NUMBER,
    PERF_LANDING_DIST_M NUMBER,
    PERF_LANDING_DIST_FT NUMBER,
    PERF_TAKEOFF_DIST_M NUMBER,
    PERF_TAKEOFF_DIST_FT NUMBER,
    PERF_CEILING_M NUMBER,
    PERF_CEILING_FT NUMBER,
    CONSTRAINT FK_BASIC_RANGE FOREIGN KEY (NAME) REFERENCES AC_BASIC(NAME)
);

-- 3. AC_SPEED
CREATE TABLE AC_SPEED (
    NAME VARCHAR2(255),
    PERF_APPROACH_SPD_KMH NUMBER,
    PERF_APPROACH_SPD_KT NUMBER,
    PERF_MAX_CRUISE_SPD_KMH NUMBER,
    PERF_MAX_CRUISE_SPD_KT NUMBER,
    CONSTRAINT FK_BASIC_SPEED FOREIGN KEY (NAME) REFERENCES AC_BASIC(NAME)
);

-- 4. AC_ENGINE_METRICS
CREATE TABLE AC_ENGINE_METRICS (
    NAME VARCHAR2(255),
    INFO_THRUST_LBF NUMBER,
    INFO_THRUST_KN NUMBER,
    INFO_POWER_SHP NUMBER,
    INFO_POWER_KW NUMBER,
    PERF_FUEL_BURN_NM_GAL NUMBER,
    PERF_FUEL_BURN_KML NUMBER,
    PERF_CLIMB_RATE_FT_MIN NUMBER,
    PERF_CLIMB_RATE_MS NUMBER,
    CONSTRAINT FK_BASIC_ENG FOREIGN KEY (NAME) REFERENCES AC_BASIC(NAME)
);

-- 5. AC_WEIGHTS
CREATE TABLE AC_WEIGHTS (
    NAME VARCHAR2(255),
    WT_MAX_TAKEOFF_KG NUMBER,
    WT_MAX_TAKEOFF_LB NUMBER,
    WT_MAX_LANDING_KG NUMBER,
    WT_MAX_LANDING_LB NUMBER,
    WT_MAX_PAYLOAD_KG NUMBER,
    WT_MAX_PAYLOAD_LB NUMBER,
    WT_FUEL_CAP_GAL NUMBER,
    WT_FUEL_CAP_L NUMBER,
    WT_FUEL_CAP_KG NUMBER,
    CONSTRAINT FK_BASIC_WT FOREIGN KEY (NAME) REFERENCES AC_BASIC(NAME)
);

-- 6. AC_DIMENSIONS
CREATE TABLE AC_DIMENSIONS (
    NAME VARCHAR2(255),
    SZ_BAGGAGE_VOL_FT3 NUMBER,
    SZ_BAGGAGE_VOL_M3 NUMBER,
    SZ_CABIN_HEIGHT_M NUMBER,
    SZ_CABIN_HEIGHT_FT NUMBER,
    SZ_CABIN_LENGTH_M NUMBER,
    SZ_CABIN_LENGTH_FT NUMBER,
    SZ_CABIN_WIDTH_M NUMBER,
    SZ_CABIN_WIDTH_FT NUMBER,
    SZ_EXTERIOR_LENGTH_M NUMBER,
    SZ_EXTERIOR_LENGTH_FT NUMBER,
    SZ_FUSELAGE_DIA_M NUMBER,
    SZ_FUSELAGE_DIA_FT NUMBER,
    SZ_TAIL_HEIGHT_M NUMBER,
    SZ_TAIL_HEIGHT_FT NUMBER,
    SZ_WING_SPAN_M NUMBER,
    SZ_WING_SPAN_FT NUMBER,
    CONSTRAINT FK_BASIC_DIM FOREIGN KEY (NAME) REFERENCES AC_BASIC(NAME)
);

-- 1. AIRLINE_IDENTITY (Ana Cədvəl)
CREATE TABLE AL_IDENTITY (
    AIRLINE_NAME VARCHAR2(255) PRIMARY KEY,
    TICKER VARCHAR2(20),
    CURRENCY VARCHAR2(10),
    EXCHANGE VARCHAR2(50)
);

-- 2. AIRLINE_FINANCE (Maliyyə göstəriciləri)
CREATE TABLE AL_FINANCE (
    AIRLINE_NAME VARCHAR2(255),
    PROFIT_MARGINS NUMBER,
    OP_MARGINS NUMBER,
    ROA NUMBER,
    ROE NUMBER,
    DEBT_TO_EQUITY NUMBER,
    TOTAL_CASH NUMBER,
    TOTAL_DEBT NUMBER,
    REVENUE_TTM NUMBER,
    EBITDA_TTM NUMBER,
    CONSTRAINT FK_AL_FINANCE FOREIGN KEY (AIRLINE_NAME) REFERENCES AL_IDENTITY(AIRLINE_NAME)
);

-- 3. AIRLINE_MARKET (Bazar göstəriciləri)
CREATE TABLE AL_MARKET (
    AIRLINE_NAME VARCHAR2(255),
    MARKET_CAP NUMBER,
    ENTERPRISE_VALUE NUMBER,
    TRAILING_PE NUMBER,
    FORWARD_PE NUMBER,
    PRICE_TO_BOOK NUMBER,
    CONSTRAINT FK_AL_MARKET FOREIGN KEY (AIRLINE_NAME) REFERENCES AL_IDENTITY(AIRLINE_NAME)
);


-- 1. Səhm Qiymətləri (AL_STOCK_PRICES)
CREATE TABLE AL_STOCK_PRICES (
    TRADE_DATE  DATE,
    TICKER      VARCHAR2(20),
    OPEN_PRICE  NUMBER,
    HIGH_PRICE  NUMBER,
    LOW_PRICE   NUMBER,
    CLOSE_PRICE NUMBER,
    VOLUME      NUMBER,
    -- Composite primary key: eyni tarixdə eyni ticker-dən iki sətir ola bilməz
    PRIMARY KEY (TRADE_DATE, TICKER)
);

-- 2. Səhm Analizi (AL_STOCK_ANALYSIS)
CREATE TABLE AL_STOCK_ANALYSIS (
    TRADE_DATE      DATE,
    TICKER          VARCHAR2(20),
    ADJ_CLOSE       NUMBER,
    DAILY_RETURN    NUMBER,
    VOLATILITY_30D  NUMBER, -- ROLLING_VOLATILITY_30D qısaldıldı
    PRIMARY KEY (TRADE_DATE, TICKER)
);


-- 1. Neft Qiymətləri Əsas (OIL_PRICES_MAIN)
CREATE TABLE OIL_PRICES_MAIN (
    TRADE_DATE      DATE,
    COMMODITY_NAME  VARCHAR2(100),
    TICKER          VARCHAR2(20),
    OPEN_PRICE      NUMBER,
    HIGH_PRICE      NUMBER,
    LOW_PRICE       NUMBER,
    CLOSE_PRICE     NUMBER,
    VOLUME          NUMBER,
    PRIMARY KEY (TRADE_DATE, TICKER)
);

-- 2. Neft Qiymətləri Analizi (OIL_PRICES_ANALYSIS)
CREATE TABLE OIL_PRICES_ANALYSIS (
    TRADE_DATE      DATE,
    TICKER          VARCHAR2(20),
    ADJ_CLOSE       NUMBER,
    DAILY_RETURN    NUMBER,
    VOLATILITY_30D  NUMBER, -- ROLLING_VOLATILITY_30D qısaldıldı
    PRIMARY KEY (TRADE_DATE, TICKER)
);

-- 1. Aviaşirkət Donanması (AL_FLEET)
CREATE TABLE AL_FLEET (
    AIRLINE_NAME    VARCHAR2(255),
    AIRCRAFT_TYPE   VARCHAR2(255),
    IN_SERVICE      NUMBER,
    PARKED          NUMBER,
    TOTAL_CURRENT   NUMBER,
    FUTURE_FLEET    NUMBER, -- FUTURE qısaldıldı
    HISTORIC        NUMBER,
    TOTAL_ALL_TIME  NUMBER,
    AVG_AGE         NUMBER, -- AVG_AGE_NUMERIC qısaldıldı
    CONSTRAINT FK_AL_FLEET FOREIGN KEY (AIRLINE_NAME) REFERENCES AL_IDENTITY(AIRLINE_NAME)
);

-- 2. Gəlir Metrikaları (AL_INCOME_METRICS)
CREATE TABLE AL_INCOME_METRICS (
    AIRLINE_NAME     VARCHAR2(255),
    TICKER           VARCHAR2(20),
    PERIOD_END       DATE,
    COST_OF_REVENUE  NUMBER,
    EBITDA           NUMBER,
    NET_INC          NUMBER, -- NET_INCOME qısaldıldı
    OP_EXPENSE       NUMBER, -- OPERATING_EXPENSE qısaldıldı
    OP_INCOME        NUMBER, -- OPERATING_INCOME qısaldıldı
    TOTAL_REVENUE    NUMBER,
    CONSTRAINT FK_AL_INCOME FOREIGN KEY (AIRLINE_NAME) REFERENCES AL_IDENTITY(AIRLINE_NAME)
);

-- 3. Ümumi Metadata (AL_METADATA)
-- Qeyd: Bu cədvəl çox böyükdür (bütün dünya şirkətləri), ona görə FK qoymuruq
CREATE TABLE AL_METADATA (
    AIRLINE_ID   NUMBER PRIMARY KEY,
    AIRLINE_NAME VARCHAR2(255), -- NAME sütunu dəyişdirildi
    IATA         VARCHAR2(10),
    ICAO         VARCHAR2(10),
    CALLSIGN     VARCHAR2(100),
    COUNTRY      VARCHAR2(100),
    IS_ACTIVE    VARCHAR2(1)   -- ACTIVE (Y/N)
);


SELECT * FROM AC_BASIC;
SELECT * FROM AC_DIMENSIONS;
SELECT * FROM AC_ENGINE_METRICS;
SELECT * FROM AC_RANGE_ALT;
SELECT * FROM AC_SPEED;
SELECT * FROM AC_WEIGHTS;
SELECT * FROM AL_FINANCE;
SELECT * FROM AL_FLEET;
SELECT * FROM AL_IDENTITY;
SELECT * FROM AL_INCOME_METRICS;
SELECT * FROM AL_MARKET;
SELECT * FROM AL_METADATA;
SELECT * FROM AL_STOCK_ANALYSIS;
SELECT * FROM AL_STOCK_PRICES;
SELECT * FROM OIL_PRICES_ANALYSIS;
SELECT * FROM OIL_PRICES_MAIN;

DROP TABLE AC_BASIC;
DROP TABLE AC_DIMENSIONS;
DROP TABLE AC_ENGINE_METRICS;
DROP TABLE AC_RANGE_ALT;
DROP TABLE AC_SPEED;
DROP TABLE AC_WEIGHTS;
DROP TABLE AL_FINANCE;
DROP TABLE AL_FLEET;
DROP TABLE AL_IDENTITY;
DROP TABLE AL_INCOME_METRICS;
DROP TABLE AL_MARKET;
DROP TABLE AL_METADATA;
DROP TABLE AL_STOCK_ANALYSIS;
DROP TABLE AL_STOCK_PRICES;
DROP TABLE OIL_PRICES_ANALYSIS;
DROP TABLE OIL_PRICES_MAIN;