-- 1. Ən Gənc və Ən Qoca Filoya (Fleet) Sahib Top Hava Yolu Şirkətləri
create table VW_FLEET_AGE_ANALYSIS as
SELECT 
    f.AIRLINE_NAME,
    ROUND(AVG(f.AVG_AGE), 1) as AVERAGE_FLEET_AGE,
    SUM(f.TOTAL_CURRENT) as TOTAL_AIRCRAFTS_IN_USE,
    RANK() OVER(ORDER BY AVG(f.AVG_AGE) ASC) as YOUNGEST_RANK
FROM al_fleet f
JOIN al_metadata m ON f.AIRLINE_NAME = m.AIRLINE_NAME
WHERE f.TOTAL_CURRENT > 0 AND m.IS_ACTIVE = 'Y'
GROUP BY f.AIRLINE_NAME
ORDER BY AVERAGE_FLEET_AGE ASC;

-- 2. Sərnişin və Yük Daşıma Gücünə (Capacity) Göre Hava Yollarının Reytinqi
create table VW_AIRLINE_CAPACITY_RANKING as
SELECT 
    fl.AIRLINE_NAME,
    COUNT(fl.AIRCRAFT_MODEL) as DIFFERENT_AIRCRAFT_TYPES,
    SUM(w.WT_MAX_PAYLOAD_KG * fl.TOTAL_CURRENT) as MAX_POTENTIAL_PAYLOAD_KG,
    ROUND(AVG(d.SZ_CABIN_WIDTH_M * d.SZ_CABIN_LENGTH_M), 2) as AVG_CABIN_AREA
FROM al_fleet fl
JOIN ac_weights w ON fl.AIRCRAFT_MODEL = w.AIRCRAFT_MODEL
JOIN ac_dimensions d ON fl.AIRCRAFT_MODEL = d.AIRCRAFT_MODEL
WHERE fl.TOTAL_CURRENT > 0
GROUP BY fl.AIRLINE_NAME
ORDER BY MAX_POTENTIAL_PAYLOAD_KG DESC NULLS LAST;

-- 3. Səhmlərin Dalğalanması (Volatility) və Neft Qiymətlərinin Əlaqəsi
create table VW_MARKET_STOCK_OIL_TRENDS as
SELECT 
    o.MONTH_YR, 
    o.AVG_OIL_PRICE, 
    s.AVG_AIRLINE_STOCK_PRICE,
    ROUND((s.AVG_AIRLINE_STOCK_PRICE / NULLIF(o.AVG_OIL_PRICE, 0)) * 100, 2) as STOCK_TO_OIL_RATIO
FROM (
    SELECT 
        TO_CHAR(TRADE_DATE, 'YYYY-MM') as MONTH_YR,
        ROUND(AVG(CLOSE_PRICE), 2) as AVG_OIL_PRICE
    FROM oil_prices_main
    GROUP BY TO_CHAR(TRADE_DATE, 'YYYY-MM')
) o
JOIN (
    SELECT 
        TO_CHAR(TRADE_DATE, 'YYYY-MM') as MONTH_YR,
        ROUND(AVG(CLOSE_PRICE), 2) as AVG_AIRLINE_STOCK_PRICE
    FROM al_stock_prices
    GROUP BY TO_CHAR(TRADE_DATE, 'YYYY-MM')
) s ON o.MONTH_YR = s.MONTH_YR
ORDER BY o.MONTH_YR DESC;

-- 4. Maksimum Tam Mənfəət əldə edən, amma Bazarda Dəyəri Aşagı olan Şirkətlər
create table VW_FINANCIAL_UNDERVALUED_AIRLINES as
SELECT 
    inc.AIRLINE_NAME,
    inc.NET_INC,
    mar.MARKET_CAP,
    ROUND(mar.MARKET_CAP / NULLIF(inc.NET_INC, 0), 2) AS PRICE_TO_EARNINGS_RATIO
FROM al_income_metrics inc
JOIN al_market mar ON inc.AIRLINE_NAME = mar.AIRLINE_NAME
WHERE inc.NET_INC > 0 
  AND inc.PERIOD_END = (SELECT MAX(PERIOD_END) FROM al_income_metrics)
ORDER BY PRICE_TO_EARNINGS_RATIO ASC;

-- 5. Təyyarə Modellərinin Təhlükəsizlik və Sürtünmə (Fuel Burn) Səmərəliliyi
create table VW_AIRCRAFT_FUEL_EFFICIENCY as
SELECT 
    basic.AIRCRAFT_MODEL,
    r.PERF_RANGE_NM,
    e.PERF_FUEL_BURN_NM_GAL,
    ROUND(r.PERF_RANGE_NM / NULLIF(e.PERF_FUEL_BURN_NM_GAL, 0), 2) as RANGE_PER_GALLON_EFFICIENCY
FROM ac_basic basic
JOIN ac_range_alt r ON basic.AIRCRAFT_MODEL = r.AIRCRAFT_MODEL
JOIN ac_engine_metrics e ON basic.AIRCRAFT_MODEL = e.AIRCRAFT_MODEL
WHERE e.PERF_FUEL_BURN_NM_GAL IS NOT NULL
ORDER BY RANGE_PER_GALLON_EFFICIENCY DESC;

-- 6. Operativ Gəlirlilik (Operational Efficiency) və Borc (Debt) Nisbəti
create table VW_OPERATIONAL_DEBT_RISK as
SELECT 
    f.AIRLINE_NAME,
    f.OP_MARGINS,
    f.TOTAL_CASH,
    f.TOTAL_DEBT,
    CASE 
        WHEN f.TOTAL_DEBT > f.TOTAL_CASH THEN 'Risky (Debt > Cash)' 
        ELSE 'Stable (Cash > Debt)' 
    END as FINANCIAL_HEALTH_STATUS
FROM al_finance f
WHERE f.OP_MARGINS IS NOT NULL
ORDER BY f.TOTAL_CASH DESC;

-- 7. Təyyarələrin Yaşına Göre Xərclərin (Op. Expenses) Artması Korelyasiyası
CREATE TABLE VW_FLEET_AGE_VS_EXPENSES AS
SELECT 
    inc.AIRLINE_NAME,
    fa.OVERALL_AVG_AGE,
    inc.OP_EXPENSE,
    inc.TOTAL_REVENUE,
    ROUND((inc.OP_EXPENSE / NULLIF(inc.TOTAL_REVENUE, 0))*100, 2) AS EXPENSE_PERCENTAGE_OF_REVENUE
FROM al_income_metrics inc
JOIN (
    SELECT AIRLINE_NAME, ROUND(AVG(AVG_AGE), 2) as OVERALL_AVG_AGE
    FROM al_fleet
    GROUP BY AIRLINE_NAME
) fa ON inc.AIRLINE_NAME = fa.AIRLINE_NAME
ORDER BY fa.OVERALL_AVG_AGE DESC;

-- 8. Gələcək Sifarişlərin (Future Fleet) Havayolu Büdcəsinə Uyğunluğu
CREATE TABLE VW_FUTURE_FLEET_EXPANSION AS
SELECT 
    pf.AIRLINE_NAME,
    pf.TOTAL_FUTURE_ORDERS,
    inc.NET_INC as CURRENT_NET_INCOME
FROM (
    SELECT AIRLINE_NAME, SUM(FUTURE_FLEET) as TOTAL_FUTURE_ORDERS
    FROM al_fleet
    GROUP BY AIRLINE_NAME
    HAVING SUM(FUTURE_FLEET) > 0
) pf
JOIN al_income_metrics inc ON pf.AIRLINE_NAME = inc.AIRLINE_NAME
ORDER BY pf.TOTAL_FUTURE_ORDERS DESC;

-- 9. Təyyarə Kabin Ölçüsünün (Comfort) və Sərnişin Sayının Əlaqəsi
CREATE TABLE VW_CABIN_COMFORT_METRICS AS
SELECT 
    d.AIRCRAFT_MODEL,
    d.SZ_CABIN_WIDTH_M * d.SZ_CABIN_LENGTH_M as ROUGH_CABIN_AREA_SQM,
    w.WT_MAX_PAYLOAD_KG,
    ROUND((d.SZ_CABIN_WIDTH_M * d.SZ_CABIN_LENGTH_M) / NULLIF(w.WT_MAX_PAYLOAD_KG,0)*1000, 3) as AREA_PER_TON_OF_PAYLOAD
FROM ac_dimensions d
JOIN ac_weights w ON d.AIRCRAFT_MODEL = w.AIRCRAFT_MODEL
WHERE d.SZ_CABIN_WIDTH_M IS NOT NULL
ORDER BY AREA_PER_TON_OF_PAYLOAD ASC;

-- 10. 52 Həftəlik Pəncərədə (Moving Average) Hava Yolu Səhmlərinin Gedişatı
CREATE TABLE VW_STOCK_MOVING_AVERAGE_30D AS
SELECT 
    TRADE_DATE,
    ROUND(CLOSE_PRICE,4) AS CLOSE_PRICES,
    ROUND(AVG(CLOSE_PRICE) OVER (ORDER BY TRADE_DATE ROWS BETWEEN 30 PRECEDING AND CURRENT ROW), 2) as MOVING_AVG_30_DAYS
FROM al_stock_prices
ORDER BY TRADE_DATE DESC;
